### ISSUE TITLE
[bug report]

### ISSUE THREAD

**Issue by Xiaoxiong-Liu** [HumaticsLAB/AttentionBasedMultiModalRNN#2]
https://github.com/HumaticsLAB/AttentionBasedMultiModalRNN/blob/2138c055f0b80bf7b8590d1e443a6827e7fe4e2c/utils.py#L32

when I run  `python train.py --data_folder dataset`

Traceback (most recent call last):
  File "train.py", line 85, in <module>
    train_dataset = CustomImageDataset(config.TRAIN_DATASET, dataset_path, transform=ds_trans)
  File "AttentionBasedMultiModalRNN-main/utils.py", line 32, in __init__
    self.color = [color_dict[x] for x in self.json_df['exact_color'].tolist()]
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/frame.py", line 2906, in __getitem__
    indexer = self.columns.get_loc(key)
  File "/usr/local/anaconda3/lib/python3.6/site-packages/pandas/core/indexes/base.py", line 2900, in get_loc
    raise KeyError(key) from err
KeyError: 'exact_color'

The 'exact_color' is not in the colums of train.csv or test.csv, should it be 'color' ?

Can you check your code again to make sure that it can run directly?
I encountered a lot of bugs when I ran this code.

**Comment by joppichristian** [comment]
Yes!
